### ISSUE TITLE
Plist config Support

### ISSUE THREAD

**Issue by AndersTao** [root3nl/SupportApp#12]
Hi

I am without access to the company's MDM, but want to deploy the app to a small group of clients I manage.
Without MDM access, I try to use a `plist`. I have created a `plist` with keys from the sample profile [nl.root3.support.plist.txt](https://github.com/root3nl/SupportApp/files/6324597/nl.root3.support.plist.txt) and placed it in /Library/Preferences, but the app doesn't seem to read the settings.

Something is happening when the `plist` is placed, the app's `CustomColor` setting change from blue to green (same color as in the sample profile)

Hope this is maybe a bug and is something that can be fixed?
If not, thanks for the app anyway, it looks great :)

**Comment by jordywitteman** [comment]
Hi @AndersTao,

We did not really focus on a non-MDM deployment but I was able to run some tests. Because the app is sandboxed, the ideal location should be `/Users/USERNAME/Library/Containers/nl.root3.support/Data/Library/Preferences/nl.root3.support.plist` in the user's home folder, but we found `/Library/Preferences/nl.root3.support.plist` also works. Other ways is installing a configuration file locally, but this cannot be automated on Big Sur anymore.

Could you try removing the nl.root3.support.plist file in all Libraries, try one of the above and restart the app? Hope it works for you as well!

**Comment by AndersTao** [comment]
Thanks for looking into this @jordywitteman 
Removing the "default" nl.root3.support.plist from `~/Library/Containers/nl.root3.support/Data/Library/Preferences` solved the problem, and the plist in `/Library/Preferences` are now read by the app 👍🏼

**Comment by jordywitteman** [comment]
Glad I could help @AndersTao! I'll mark the issue as closed.
