### ISSUE TITLE
Feature Request - Utilize the Self Service branding

### ISSUE THREAD

**Issue by salesloftcb** [root3nl/SupportApp#27]
Another request: we've already got `/Users/$USERNAME/Library/Application Support/com.jamfsoftware.selfservice.mac/Documents/Images/brandingimage.png` deployed from our Jamf Self Service app with custom branding, would it be possible to utilize that png file instead of having to deploy a second or is it a file resolution/sandboxing limitation to using that one?

**Comment by dan-snelson** [comment]
@salesloftcb We're testing the following [Support Post-install](https://github.com/dan-snelson/Support-Post-install/blob/main/Support-Post-install.bash#L113) script to leverage `brandingimage.png`.

**Comment by jordywitteman** [comment]
Hi @dan-snelson that's awesome! Great workaround as we are unable to directly use the Self Service branding due to App Sandbox. We think App Sandbox is an important security feature and we don't want to disable it.

@salesloftcb As lots of admins are requesting a custom app icon, this is one of the top priorities for an upcoming release!

**Comment by jordywitteman** [comment]
Hi @salesloftcb in version 2.3 we've added the possibility to modify the icon in alert windows and the about window. Use the key **NotificationIcon** and restart the app.

Using the Self Service will be hard to implement with App Sandbox. Now that it's open source, perhaps someone knows how to do it :)

**Comment by jordywitteman** [comment]
Will close this one as we believe this will not be possible without compromising the App Sandbox. Please reopen if proven otherwise
