### ISSUE TITLE
StatusBarIcon appears only in B&W

### ISSUE THREAD

**Issue by precursorca** [root3nl/SupportApp#59]
A Colour PNG seems to appear only as a solid black object when used as the StatusBarIcon

**Comment by jordywitteman** [comment]
Hi @precursorca this is expected behaviour as we follow Apple's Human Interface Guidelines as much as possible: https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/

Icons are masked to adapt to the macOS appearance settings such as wallpaper and light/dark mode. If there are details inside the your PNG object, those need to be made transparant in the PNG to make it visible. Off course not all logos or images are great to be used in the menu bar and then we suggest using a matching SF Symbol instead.

Hope it helps!
