### ISSUE TITLE
Feature Request: Show MDM update remaining deferrals

### ISSUE THREAD

**Issue by jordywitteman** [root3nl/SupportApp#98]
Find an intuitive and informative way to show the remaining deferrals for macOS updates when using MDM commands in the macOS version info item. This should integrate with `MaxUserDeferrals` from the [ScheduleOSUpdate](https://developer.apple.com/documentation/devicemanagement/scheduleosupdatecommand/command/updatesitem) command. The deferral count and max count is written in `com.apple.SoftwareUpdate` so it can be easily calculated how many deferrals are remaining before the Mac tries to install the update overnight

**Comment by jordywitteman** [comment]
Closing this issue as [ScheduleOSUpdate](https://developer.apple.com/documentation/devicemanagement/scheduleosupdatecommand/command/updatesitem) is still somewhat unreliable. Also macOS Sonoma will introduce better ways to manage software updates using declarative device management. We expect MDM commands to become legacy so it doesn't make sense to invest in integrating with it. We may revisit when macOS Sonoma comes out to provide more update enforcement information if possible

**Comment by wakco** [comment]
I'd also like to add, as a reminder, there are two extension buttons, and the entire bottom section (totalling up to 8 buttons)that can be customised to show what you maybe after, for example, I do not use Support apps standard macOS Version button, I have an extension button setup to report on if the macOS version is still in support as well as the version, and clicking it will start the super (or S.U.P.E.R.M.A.N.) script to perform updates, instead of taking the user to the Software Updates pane of System Preferences/Settings.
